---
crc_version: "latest"
crc_url: "https://mirror.openshift.com/pub/openshift-v4/clients/crc/{{ crc_version }}/crc-linux-amd64.tar.xz"

crc_cpus: 4
crc_memory: 10752
crc_disk: 35

pull_secret_path: "{{ playbook_dir }}/pull-secret.txt"

crc_bin_dir: "{{ playbook_dir }}/bin/crc"
crc_binary: "{{ crc_bin_dir }}/crc"

crc_preset: "openshift"
crc_enable_cluster_monitoring: false
